// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: api/protos/add.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на добавление username и password
type AddUsernamePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUsernamePasswordRequest) Reset() {
	*x = AddUsernamePasswordRequest{}
	mi := &file_api_protos_add_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUsernamePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUsernamePasswordRequest) ProtoMessage() {}

func (x *AddUsernamePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_add_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUsernamePasswordRequest.ProtoReflect.Descriptor instead.
func (*AddUsernamePasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_add_proto_rawDescGZIP(), []int{0}
}

func (x *AddUsernamePasswordRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AddUsernamePasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AddUsernamePasswordRequest) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

// Ответ с ошибкой (пустая строка — без ошибок)
type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_api_protos_add_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_add_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_add_proto_rawDescGZIP(), []int{1}
}

func (x *AddResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Запрос на добавление произвольного текста
type AddTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,2,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTextRequest) Reset() {
	*x = AddTextRequest{}
	mi := &file_api_protos_add_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTextRequest) ProtoMessage() {}

func (x *AddTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_add_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTextRequest.ProtoReflect.Descriptor instead.
func (*AddTextRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_add_proto_rawDescGZIP(), []int{2}
}

func (x *AddTextRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddTextRequest) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

// Запрос на добавление бинарных данных
type AddBinaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,2,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBinaryRequest) Reset() {
	*x = AddBinaryRequest{}
	mi := &file_api_protos_add_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBinaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBinaryRequest) ProtoMessage() {}

func (x *AddBinaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_add_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBinaryRequest.ProtoReflect.Descriptor instead.
func (*AddBinaryRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_add_proto_rawDescGZIP(), []int{3}
}

func (x *AddBinaryRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AddBinaryRequest) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

// Запрос на добавление данных банковской карты
type AddBankCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Expiry        string                 `protobuf:"bytes,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Cvv           string                 `protobuf:"bytes,4,opt,name=cvv,proto3" json:"cvv,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,5,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBankCardRequest) Reset() {
	*x = AddBankCardRequest{}
	mi := &file_api_protos_add_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBankCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBankCardRequest) ProtoMessage() {}

func (x *AddBankCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_add_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBankCardRequest.ProtoReflect.Descriptor instead.
func (*AddBankCardRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_add_proto_rawDescGZIP(), []int{4}
}

func (x *AddBankCardRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *AddBankCardRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *AddBankCardRequest) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *AddBankCardRequest) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *AddBankCardRequest) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_api_protos_add_proto protoreflect.FileDescriptor

const file_api_protos_add_proto_rawDesc = "" +
	"\n" +
	"\x14api/protos/add.proto\x12\x0fgophkeeper.grpc\"\xd8\x01\n" +
	"\x1aAddUsernamePasswordRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12I\n" +
	"\x04meta\x18\x03 \x03(\v25.gophkeeper.grpc.AddUsernamePasswordRequest.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"#\n" +
	"\vAddResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xa2\x01\n" +
	"\x0eAddTextRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12=\n" +
	"\x04meta\x18\x02 \x03(\v2).gophkeeper.grpc.AddTextRequest.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x01\n" +
	"\x10AddBinaryRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12?\n" +
	"\x04meta\x18\x02 \x03(\v2+.gophkeeper.grpc.AddBinaryRequest.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe8\x01\n" +
	"\x12AddBankCardRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x16\n" +
	"\x06expiry\x18\x03 \x01(\tR\x06expiry\x12\x10\n" +
	"\x03cvv\x18\x04 \x01(\tR\x03cvv\x12A\n" +
	"\x04meta\x18\x05 \x03(\v2-.gophkeeper.grpc.AddBankCardRequest.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xd8\x02\n" +
	"\n" +
	"AddService\x12`\n" +
	"\x13AddUsernamePassword\x12+.gophkeeper.grpc.AddUsernamePasswordRequest\x1a\x1c.gophkeeper.grpc.AddResponse\x12H\n" +
	"\aAddText\x12\x1f.gophkeeper.grpc.AddTextRequest\x1a\x1c.gophkeeper.grpc.AddResponse\x12L\n" +
	"\tAddBinary\x12!.gophkeeper.grpc.AddBinaryRequest\x1a\x1c.gophkeeper.grpc.AddResponse\x12P\n" +
	"\vAddBankCard\x12#.gophkeeper.grpc.AddBankCardRequest\x1a\x1c.gophkeeper.grpc.AddResponseB2Z0github.com/sbilibin2017/gophkeeper/pkg/grpc;grpcb\x06proto3"

var (
	file_api_protos_add_proto_rawDescOnce sync.Once
	file_api_protos_add_proto_rawDescData []byte
)

func file_api_protos_add_proto_rawDescGZIP() []byte {
	file_api_protos_add_proto_rawDescOnce.Do(func() {
		file_api_protos_add_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protos_add_proto_rawDesc), len(file_api_protos_add_proto_rawDesc)))
	})
	return file_api_protos_add_proto_rawDescData
}

var file_api_protos_add_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_protos_add_proto_goTypes = []any{
	(*AddUsernamePasswordRequest)(nil), // 0: gophkeeper.grpc.AddUsernamePasswordRequest
	(*AddResponse)(nil),                // 1: gophkeeper.grpc.AddResponse
	(*AddTextRequest)(nil),             // 2: gophkeeper.grpc.AddTextRequest
	(*AddBinaryRequest)(nil),           // 3: gophkeeper.grpc.AddBinaryRequest
	(*AddBankCardRequest)(nil),         // 4: gophkeeper.grpc.AddBankCardRequest
	nil,                                // 5: gophkeeper.grpc.AddUsernamePasswordRequest.MetaEntry
	nil,                                // 6: gophkeeper.grpc.AddTextRequest.MetaEntry
	nil,                                // 7: gophkeeper.grpc.AddBinaryRequest.MetaEntry
	nil,                                // 8: gophkeeper.grpc.AddBankCardRequest.MetaEntry
}
var file_api_protos_add_proto_depIdxs = []int32{
	5, // 0: gophkeeper.grpc.AddUsernamePasswordRequest.meta:type_name -> gophkeeper.grpc.AddUsernamePasswordRequest.MetaEntry
	6, // 1: gophkeeper.grpc.AddTextRequest.meta:type_name -> gophkeeper.grpc.AddTextRequest.MetaEntry
	7, // 2: gophkeeper.grpc.AddBinaryRequest.meta:type_name -> gophkeeper.grpc.AddBinaryRequest.MetaEntry
	8, // 3: gophkeeper.grpc.AddBankCardRequest.meta:type_name -> gophkeeper.grpc.AddBankCardRequest.MetaEntry
	0, // 4: gophkeeper.grpc.AddService.AddUsernamePassword:input_type -> gophkeeper.grpc.AddUsernamePasswordRequest
	2, // 5: gophkeeper.grpc.AddService.AddText:input_type -> gophkeeper.grpc.AddTextRequest
	3, // 6: gophkeeper.grpc.AddService.AddBinary:input_type -> gophkeeper.grpc.AddBinaryRequest
	4, // 7: gophkeeper.grpc.AddService.AddBankCard:input_type -> gophkeeper.grpc.AddBankCardRequest
	1, // 8: gophkeeper.grpc.AddService.AddUsernamePassword:output_type -> gophkeeper.grpc.AddResponse
	1, // 9: gophkeeper.grpc.AddService.AddText:output_type -> gophkeeper.grpc.AddResponse
	1, // 10: gophkeeper.grpc.AddService.AddBinary:output_type -> gophkeeper.grpc.AddResponse
	1, // 11: gophkeeper.grpc.AddService.AddBankCard:output_type -> gophkeeper.grpc.AddResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_protos_add_proto_init() }
func file_api_protos_add_proto_init() {
	if File_api_protos_add_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protos_add_proto_rawDesc), len(file_api_protos_add_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protos_add_proto_goTypes,
		DependencyIndexes: file_api_protos_add_proto_depIdxs,
		MessageInfos:      file_api_protos_add_proto_msgTypes,
	}.Build()
	File_api_protos_add_proto = out.File
	file_api_protos_add_proto_goTypes = nil
	file_api_protos_add_proto_depIdxs = nil
}
