// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: api/protos/add.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_api_protos_add_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_add_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_add_proto_rawDescGZIP(), []int{0}
}

func (x *AddResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_protos_add_proto protoreflect.FileDescriptor

const file_api_protos_add_proto_rawDesc = "" +
	"\n" +
	"\x14api/protos/add.proto\x12\x0fgophkeeper.grpc\x1a\x17api/protos/secret.proto\"#\n" +
	"\vAddResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2k\n" +
	"\x17AddLoginPasswordService\x12P\n" +
	"\x10AddLoginPassword\x12\x1e.gophkeeper.grpc.LoginPassword\x1a\x1c.gophkeeper.grpc.AddResponse2P\n" +
	"\x0eAddTextService\x12>\n" +
	"\aAddText\x12\x15.gophkeeper.grpc.Text\x1a\x1c.gophkeeper.grpc.AddResponse2V\n" +
	"\x10AddBinaryService\x12B\n" +
	"\tAddBinary\x12\x17.gophkeeper.grpc.Binary\x1a\x1c.gophkeeper.grpc.AddResponse2P\n" +
	"\x0eAddCardService\x12>\n" +
	"\aAddCard\x12\x15.gophkeeper.grpc.Card\x1a\x1c.gophkeeper.grpc.AddResponseB-Z+github.com/sbilibin2017/gophkeeper/pkg/grpcb\x06proto3"

var (
	file_api_protos_add_proto_rawDescOnce sync.Once
	file_api_protos_add_proto_rawDescData []byte
)

func file_api_protos_add_proto_rawDescGZIP() []byte {
	file_api_protos_add_proto_rawDescOnce.Do(func() {
		file_api_protos_add_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protos_add_proto_rawDesc), len(file_api_protos_add_proto_rawDesc)))
	})
	return file_api_protos_add_proto_rawDescData
}

var file_api_protos_add_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_protos_add_proto_goTypes = []any{
	(*AddResponse)(nil),   // 0: gophkeeper.grpc.AddResponse
	(*LoginPassword)(nil), // 1: gophkeeper.grpc.LoginPassword
	(*Text)(nil),          // 2: gophkeeper.grpc.Text
	(*Binary)(nil),        // 3: gophkeeper.grpc.Binary
	(*Card)(nil),          // 4: gophkeeper.grpc.Card
}
var file_api_protos_add_proto_depIdxs = []int32{
	1, // 0: gophkeeper.grpc.AddLoginPasswordService.AddLoginPassword:input_type -> gophkeeper.grpc.LoginPassword
	2, // 1: gophkeeper.grpc.AddTextService.AddText:input_type -> gophkeeper.grpc.Text
	3, // 2: gophkeeper.grpc.AddBinaryService.AddBinary:input_type -> gophkeeper.grpc.Binary
	4, // 3: gophkeeper.grpc.AddCardService.AddCard:input_type -> gophkeeper.grpc.Card
	0, // 4: gophkeeper.grpc.AddLoginPasswordService.AddLoginPassword:output_type -> gophkeeper.grpc.AddResponse
	0, // 5: gophkeeper.grpc.AddTextService.AddText:output_type -> gophkeeper.grpc.AddResponse
	0, // 6: gophkeeper.grpc.AddBinaryService.AddBinary:output_type -> gophkeeper.grpc.AddResponse
	0, // 7: gophkeeper.grpc.AddCardService.AddCard:output_type -> gophkeeper.grpc.AddResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_protos_add_proto_init() }
func file_api_protos_add_proto_init() {
	if File_api_protos_add_proto != nil {
		return
	}
	file_api_protos_secret_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protos_add_proto_rawDesc), len(file_api_protos_add_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_api_protos_add_proto_goTypes,
		DependencyIndexes: file_api_protos_add_proto_depIdxs,
		MessageInfos:      file_api_protos_add_proto_msgTypes,
	}.Build()
	File_api_protos_add_proto = out.File
	file_api_protos_add_proto_goTypes = nil
	file_api_protos_add_proto_depIdxs = nil
}
