// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: api/protos/add.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AddService_AddLoginPassword_FullMethodName = "/gophkeeper.grpc.AddService/AddLoginPassword"
	AddService_AddText_FullMethodName          = "/gophkeeper.grpc.AddService/AddText"
	AddService_AddBinary_FullMethodName        = "/gophkeeper.grpc.AddService/AddBinary"
	AddService_AddCard_FullMethodName          = "/gophkeeper.grpc.AddService/AddCard"
)

// AddServiceClient is the client API for AddService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AddService provides secret storing functionality.
type AddServiceClient interface {
	// AddLoginPassword adds a login/password secret.
	AddLoginPassword(ctx context.Context, in *LoginPassword, opts ...grpc.CallOption) (*AddResponse, error)
	// AddText adds a textual secret.
	AddText(ctx context.Context, in *Text, opts ...grpc.CallOption) (*AddResponse, error)
	// AddBinary adds a binary secret.
	AddBinary(ctx context.Context, in *Binary, opts ...grpc.CallOption) (*AddResponse, error)
	// AddCard adds a card secret.
	AddCard(ctx context.Context, in *Card, opts ...grpc.CallOption) (*AddResponse, error)
}

type addServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAddServiceClient(cc grpc.ClientConnInterface) AddServiceClient {
	return &addServiceClient{cc}
}

func (c *addServiceClient) AddLoginPassword(ctx context.Context, in *LoginPassword, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, AddService_AddLoginPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) AddText(ctx context.Context, in *Text, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, AddService_AddText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) AddBinary(ctx context.Context, in *Binary, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, AddService_AddBinary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) AddCard(ctx context.Context, in *Card, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, AddService_AddCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddServiceServer is the server API for AddService service.
// All implementations must embed UnimplementedAddServiceServer
// for forward compatibility.
//
// AddService provides secret storing functionality.
type AddServiceServer interface {
	// AddLoginPassword adds a login/password secret.
	AddLoginPassword(context.Context, *LoginPassword) (*AddResponse, error)
	// AddText adds a textual secret.
	AddText(context.Context, *Text) (*AddResponse, error)
	// AddBinary adds a binary secret.
	AddBinary(context.Context, *Binary) (*AddResponse, error)
	// AddCard adds a card secret.
	AddCard(context.Context, *Card) (*AddResponse, error)
	mustEmbedUnimplementedAddServiceServer()
}

// UnimplementedAddServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAddServiceServer struct{}

func (UnimplementedAddServiceServer) AddLoginPassword(context.Context, *LoginPassword) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLoginPassword not implemented")
}
func (UnimplementedAddServiceServer) AddText(context.Context, *Text) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddText not implemented")
}
func (UnimplementedAddServiceServer) AddBinary(context.Context, *Binary) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBinary not implemented")
}
func (UnimplementedAddServiceServer) AddCard(context.Context, *Card) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCard not implemented")
}
func (UnimplementedAddServiceServer) mustEmbedUnimplementedAddServiceServer() {}
func (UnimplementedAddServiceServer) testEmbeddedByValue()                    {}

// UnsafeAddServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddServiceServer will
// result in compilation errors.
type UnsafeAddServiceServer interface {
	mustEmbedUnimplementedAddServiceServer()
}

func RegisterAddServiceServer(s grpc.ServiceRegistrar, srv AddServiceServer) {
	// If the following call pancis, it indicates UnimplementedAddServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AddService_ServiceDesc, srv)
}

func _AddService_AddLoginPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginPassword)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).AddLoginPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddService_AddLoginPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).AddLoginPassword(ctx, req.(*LoginPassword))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_AddText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Text)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).AddText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddService_AddText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).AddText(ctx, req.(*Text))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_AddBinary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Binary)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).AddBinary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddService_AddBinary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).AddBinary(ctx, req.(*Binary))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_AddCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Card)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).AddCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddService_AddCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).AddCard(ctx, req.(*Card))
	}
	return interceptor(ctx, in, info, handler)
}

// AddService_ServiceDesc is the grpc.ServiceDesc for AddService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AddService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gophkeeper.grpc.AddService",
	HandlerType: (*AddServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddLoginPassword",
			Handler:    _AddService_AddLoginPassword_Handler,
		},
		{
			MethodName: "AddText",
			Handler:    _AddService_AddText_Handler,
		},
		{
			MethodName: "AddBinary",
			Handler:    _AddService_AddBinary_Handler,
		},
		{
			MethodName: "AddCard",
			Handler:    _AddService_AddCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/protos/add.proto",
}
