// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: bankcard.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BankCardAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Exp           string                 `protobuf:"bytes,4,opt,name=exp,proto3" json:"exp,omitempty"`
	Cvv           string                 `protobuf:"bytes,5,opt,name=cvv,proto3" json:"cvv,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,6,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankCardAddRequest) Reset() {
	*x = BankCardAddRequest{}
	mi := &file_bankcard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankCardAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankCardAddRequest) ProtoMessage() {}

func (x *BankCardAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bankcard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankCardAddRequest.ProtoReflect.Descriptor instead.
func (*BankCardAddRequest) Descriptor() ([]byte, []int) {
	return file_bankcard_proto_rawDescGZIP(), []int{0}
}

func (x *BankCardAddRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *BankCardAddRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *BankCardAddRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *BankCardAddRequest) GetExp() string {
	if x != nil {
		return x.Exp
	}
	return ""
}

func (x *BankCardAddRequest) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *BankCardAddRequest) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type BankCardFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankCardFilterRequest) Reset() {
	*x = BankCardFilterRequest{}
	mi := &file_bankcard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankCardFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankCardFilterRequest) ProtoMessage() {}

func (x *BankCardFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bankcard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankCardFilterRequest.ProtoReflect.Descriptor instead.
func (*BankCardFilterRequest) Descriptor() ([]byte, []int) {
	return file_bankcard_proto_rawDescGZIP(), []int{1}
}

func (x *BankCardFilterRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

type BankCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretOwner   string                 `protobuf:"bytes,2,opt,name=secret_owner,json=secretOwner,proto3" json:"secret_owner,omitempty"`
	Number        string                 `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Exp           string                 `protobuf:"bytes,5,opt,name=exp,proto3" json:"exp,omitempty"`
	Cvv           string                 `protobuf:"bytes,6,opt,name=cvv,proto3" json:"cvv,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,7,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankCard) Reset() {
	*x = BankCard{}
	mi := &file_bankcard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankCard) ProtoMessage() {}

func (x *BankCard) ProtoReflect() protoreflect.Message {
	mi := &file_bankcard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankCard.ProtoReflect.Descriptor instead.
func (*BankCard) Descriptor() ([]byte, []int) {
	return file_bankcard_proto_rawDescGZIP(), []int{2}
}

func (x *BankCard) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *BankCard) GetSecretOwner() string {
	if x != nil {
		return x.SecretOwner
	}
	return ""
}

func (x *BankCard) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *BankCard) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *BankCard) GetExp() string {
	if x != nil {
		return x.Exp
	}
	return ""
}

func (x *BankCard) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *BankCard) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *BankCard) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_bankcard_proto protoreflect.FileDescriptor

const file_bankcard_proto_rawDesc = "" +
	"\n" +
	"\x0ebankcard.proto\x12\bbankcard\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfc\x01\n" +
	"\x12BankCardAddRequest\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x10\n" +
	"\x03exp\x18\x04 \x01(\tR\x03exp\x12\x10\n" +
	"\x03cvv\x18\x05 \x01(\tR\x03cvv\x12:\n" +
	"\x04meta\x18\x06 \x03(\v2&.bankcard.BankCardAddRequest.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\x15BankCardFilterRequest\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\"\xc6\x02\n" +
	"\bBankCard\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\x12!\n" +
	"\fsecret_owner\x18\x02 \x01(\tR\vsecretOwner\x12\x16\n" +
	"\x06number\x18\x03 \x01(\tR\x06number\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x10\n" +
	"\x03exp\x18\x05 \x01(\tR\x03exp\x12\x10\n" +
	"\x03cvv\x18\x06 \x01(\tR\x03cvv\x120\n" +
	"\x04meta\x18\a \x03(\v2\x1c.bankcard.BankCard.MetaEntryR\x04meta\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xc0\x01\n" +
	"\x0fBankCardService\x12;\n" +
	"\x03Add\x12\x1c.bankcard.BankCardAddRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\x03Get\x12\x1f.bankcard.BankCardFilterRequest\x1a\x12.bankcard.BankCard\x124\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\x12.bankcard.BankCard0\x01B-Z+github.com/sbilibin2017/gophkeeper/pkg/grpcb\x06proto3"

var (
	file_bankcard_proto_rawDescOnce sync.Once
	file_bankcard_proto_rawDescData []byte
)

func file_bankcard_proto_rawDescGZIP() []byte {
	file_bankcard_proto_rawDescOnce.Do(func() {
		file_bankcard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bankcard_proto_rawDesc), len(file_bankcard_proto_rawDesc)))
	})
	return file_bankcard_proto_rawDescData
}

var file_bankcard_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_bankcard_proto_goTypes = []any{
	(*BankCardAddRequest)(nil),    // 0: bankcard.BankCardAddRequest
	(*BankCardFilterRequest)(nil), // 1: bankcard.BankCardFilterRequest
	(*BankCard)(nil),              // 2: bankcard.BankCard
	nil,                           // 3: bankcard.BankCardAddRequest.MetaEntry
	nil,                           // 4: bankcard.BankCard.MetaEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_bankcard_proto_depIdxs = []int32{
	3, // 0: bankcard.BankCardAddRequest.meta:type_name -> bankcard.BankCardAddRequest.MetaEntry
	4, // 1: bankcard.BankCard.meta:type_name -> bankcard.BankCard.MetaEntry
	5, // 2: bankcard.BankCard.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: bankcard.BankCardService.Add:input_type -> bankcard.BankCardAddRequest
	1, // 4: bankcard.BankCardService.Get:input_type -> bankcard.BankCardFilterRequest
	6, // 5: bankcard.BankCardService.List:input_type -> google.protobuf.Empty
	6, // 6: bankcard.BankCardService.Add:output_type -> google.protobuf.Empty
	2, // 7: bankcard.BankCardService.Get:output_type -> bankcard.BankCard
	2, // 8: bankcard.BankCardService.List:output_type -> bankcard.BankCard
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bankcard_proto_init() }
func file_bankcard_proto_init() {
	if File_bankcard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bankcard_proto_rawDesc), len(file_bankcard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bankcard_proto_goTypes,
		DependencyIndexes: file_bankcard_proto_depIdxs,
		MessageInfos:      file_bankcard_proto_msgTypes,
	}.Build()
	File_bankcard_proto = out.File
	file_bankcard_proto_goTypes = nil
	file_bankcard_proto_depIdxs = nil
}
