// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: api/protos/get.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	SecretId      string                 `protobuf:"bytes,2,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_protos_get_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_get_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_get_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

type GetLoginPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoginPassword *LoginPassword         `protobuf:"bytes,1,opt,name=login_password,json=loginPassword,proto3" json:"login_password,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginPasswordResponse) Reset() {
	*x = GetLoginPasswordResponse{}
	mi := &file_api_protos_get_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginPasswordResponse) ProtoMessage() {}

func (x *GetLoginPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_get_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginPasswordResponse.ProtoReflect.Descriptor instead.
func (*GetLoginPasswordResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_get_proto_rawDescGZIP(), []int{1}
}

func (x *GetLoginPasswordResponse) GetLoginPassword() *LoginPassword {
	if x != nil {
		return x.LoginPassword
	}
	return nil
}

func (x *GetLoginPasswordResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          *Text                  `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTextResponse) Reset() {
	*x = GetTextResponse{}
	mi := &file_api_protos_get_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTextResponse) ProtoMessage() {}

func (x *GetTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_get_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTextResponse.ProtoReflect.Descriptor instead.
func (*GetTextResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_get_proto_rawDescGZIP(), []int{2}
}

func (x *GetTextResponse) GetText() *Text {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *GetTextResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetBinaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Binary        *Binary                `protobuf:"bytes,1,opt,name=binary,proto3" json:"binary,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBinaryResponse) Reset() {
	*x = GetBinaryResponse{}
	mi := &file_api_protos_get_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBinaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBinaryResponse) ProtoMessage() {}

func (x *GetBinaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_get_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBinaryResponse.ProtoReflect.Descriptor instead.
func (*GetBinaryResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_get_proto_rawDescGZIP(), []int{3}
}

func (x *GetBinaryResponse) GetBinary() *Binary {
	if x != nil {
		return x.Binary
	}
	return nil
}

func (x *GetBinaryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardResponse) Reset() {
	*x = GetCardResponse{}
	mi := &file_api_protos_get_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardResponse) ProtoMessage() {}

func (x *GetCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_get_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardResponse.ProtoReflect.Descriptor instead.
func (*GetCardResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_get_proto_rawDescGZIP(), []int{4}
}

func (x *GetCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *GetCardResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_protos_get_proto protoreflect.FileDescriptor

const file_api_protos_get_proto_rawDesc = "" +
	"\n" +
	"\x14api/protos/get.proto\x12\x0fgophkeeper.grpc\x1a\x17api/protos/secret.proto\"?\n" +
	"\n" +
	"GetRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tsecret_id\x18\x02 \x01(\tR\bsecretId\"w\n" +
	"\x18GetLoginPasswordResponse\x12E\n" +
	"\x0elogin_password\x18\x01 \x01(\v2\x1e.gophkeeper.grpc.LoginPasswordR\rloginPassword\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"R\n" +
	"\x0fGetTextResponse\x12)\n" +
	"\x04text\x18\x01 \x01(\v2\x15.gophkeeper.grpc.TextR\x04text\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"Z\n" +
	"\x11GetBinaryResponse\x12/\n" +
	"\x06binary\x18\x01 \x01(\v2\x17.gophkeeper.grpc.BinaryR\x06binary\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"R\n" +
	"\x0fGetCardResponse\x12)\n" +
	"\x04card\x18\x01 \x01(\v2\x15.gophkeeper.grpc.CardR\x04card\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2h\n" +
	"\x17GetLoginPasswordService\x12M\n" +
	"\x03Get\x12\x1b.gophkeeper.grpc.GetRequest\x1a).gophkeeper.grpc.GetLoginPasswordResponse2V\n" +
	"\x0eGetTextService\x12D\n" +
	"\x03Get\x12\x1b.gophkeeper.grpc.GetRequest\x1a .gophkeeper.grpc.GetTextResponse2Z\n" +
	"\x10GetBinaryService\x12F\n" +
	"\x03Get\x12\x1b.gophkeeper.grpc.GetRequest\x1a\".gophkeeper.grpc.GetBinaryResponse2V\n" +
	"\x0eGetCardService\x12D\n" +
	"\x03Get\x12\x1b.gophkeeper.grpc.GetRequest\x1a .gophkeeper.grpc.GetCardResponseB-Z+github.com/sbilibin2017/gophkeeper/pkg/grpcb\x06proto3"

var (
	file_api_protos_get_proto_rawDescOnce sync.Once
	file_api_protos_get_proto_rawDescData []byte
)

func file_api_protos_get_proto_rawDescGZIP() []byte {
	file_api_protos_get_proto_rawDescOnce.Do(func() {
		file_api_protos_get_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protos_get_proto_rawDesc), len(file_api_protos_get_proto_rawDesc)))
	})
	return file_api_protos_get_proto_rawDescData
}

var file_api_protos_get_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_protos_get_proto_goTypes = []any{
	(*GetRequest)(nil),               // 0: gophkeeper.grpc.GetRequest
	(*GetLoginPasswordResponse)(nil), // 1: gophkeeper.grpc.GetLoginPasswordResponse
	(*GetTextResponse)(nil),          // 2: gophkeeper.grpc.GetTextResponse
	(*GetBinaryResponse)(nil),        // 3: gophkeeper.grpc.GetBinaryResponse
	(*GetCardResponse)(nil),          // 4: gophkeeper.grpc.GetCardResponse
	(*LoginPassword)(nil),            // 5: gophkeeper.grpc.LoginPassword
	(*Text)(nil),                     // 6: gophkeeper.grpc.Text
	(*Binary)(nil),                   // 7: gophkeeper.grpc.Binary
	(*Card)(nil),                     // 8: gophkeeper.grpc.Card
}
var file_api_protos_get_proto_depIdxs = []int32{
	5, // 0: gophkeeper.grpc.GetLoginPasswordResponse.login_password:type_name -> gophkeeper.grpc.LoginPassword
	6, // 1: gophkeeper.grpc.GetTextResponse.text:type_name -> gophkeeper.grpc.Text
	7, // 2: gophkeeper.grpc.GetBinaryResponse.binary:type_name -> gophkeeper.grpc.Binary
	8, // 3: gophkeeper.grpc.GetCardResponse.card:type_name -> gophkeeper.grpc.Card
	0, // 4: gophkeeper.grpc.GetLoginPasswordService.Get:input_type -> gophkeeper.grpc.GetRequest
	0, // 5: gophkeeper.grpc.GetTextService.Get:input_type -> gophkeeper.grpc.GetRequest
	0, // 6: gophkeeper.grpc.GetBinaryService.Get:input_type -> gophkeeper.grpc.GetRequest
	0, // 7: gophkeeper.grpc.GetCardService.Get:input_type -> gophkeeper.grpc.GetRequest
	1, // 8: gophkeeper.grpc.GetLoginPasswordService.Get:output_type -> gophkeeper.grpc.GetLoginPasswordResponse
	2, // 9: gophkeeper.grpc.GetTextService.Get:output_type -> gophkeeper.grpc.GetTextResponse
	3, // 10: gophkeeper.grpc.GetBinaryService.Get:output_type -> gophkeeper.grpc.GetBinaryResponse
	4, // 11: gophkeeper.grpc.GetCardService.Get:output_type -> gophkeeper.grpc.GetCardResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_protos_get_proto_init() }
func file_api_protos_get_proto_init() {
	if File_api_protos_get_proto != nil {
		return
	}
	file_api_protos_secret_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protos_get_proto_rawDesc), len(file_api_protos_get_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_api_protos_get_proto_goTypes,
		DependencyIndexes: file_api_protos_get_proto_depIdxs,
		MessageInfos:      file_api_protos_get_proto_msgTypes,
	}.Build()
	File_api_protos_get_proto = out.File
	file_api_protos_get_proto_goTypes = nil
	file_api_protos_get_proto_depIdxs = nil
}
