// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: api/protos/install.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос с указанием платформы (os и arch)
type InstallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`     // например "windows", "linux", "darwin"
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"` // например "amd64", "arm64"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallRequest) Reset() {
	*x = InstallRequest{}
	mi := &file_api_protos_install_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallRequest) ProtoMessage() {}

func (x *InstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_install_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallRequest.ProtoReflect.Descriptor instead.
func (*InstallRequest) Descriptor() ([]byte, []int) {
	return file_api_protos_install_proto_rawDescGZIP(), []int{0}
}

func (x *InstallRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *InstallRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

// Ответ с бинарными данными клиента
type InstallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BinaryData    []byte                 `protobuf:"bytes,1,opt,name=binary_data,json=binaryData,proto3" json:"binary_data,omitempty"` // бинарный файл клиента
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`       // имя файла с расширением
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                             // пусто, если ошибок нет
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallResponse) Reset() {
	*x = InstallResponse{}
	mi := &file_api_protos_install_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallResponse) ProtoMessage() {}

func (x *InstallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protos_install_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallResponse.ProtoReflect.Descriptor instead.
func (*InstallResponse) Descriptor() ([]byte, []int) {
	return file_api_protos_install_proto_rawDescGZIP(), []int{1}
}

func (x *InstallResponse) GetBinaryData() []byte {
	if x != nil {
		return x.BinaryData
	}
	return nil
}

func (x *InstallResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *InstallResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_protos_install_proto protoreflect.FileDescriptor

const file_api_protos_install_proto_rawDesc = "" +
	"\n" +
	"\x18api/protos/install.proto\x12\x0fgophkeeper.grpc\"4\n" +
	"\x0eInstallRequest\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\"e\n" +
	"\x0fInstallResponse\x12\x1f\n" +
	"\vbinary_data\x18\x01 \x01(\fR\n" +
	"binaryData\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2k\n" +
	"\x14ClientInstallService\x12S\n" +
	"\x0eDownloadClient\x12\x1f.gophkeeper.grpc.InstallRequest\x1a .gophkeeper.grpc.InstallResponseB-Z+github.com/sbilibin2017/gophkeeper/pkg/grpcb\x06proto3"

var (
	file_api_protos_install_proto_rawDescOnce sync.Once
	file_api_protos_install_proto_rawDescData []byte
)

func file_api_protos_install_proto_rawDescGZIP() []byte {
	file_api_protos_install_proto_rawDescOnce.Do(func() {
		file_api_protos_install_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protos_install_proto_rawDesc), len(file_api_protos_install_proto_rawDesc)))
	})
	return file_api_protos_install_proto_rawDescData
}

var file_api_protos_install_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_protos_install_proto_goTypes = []any{
	(*InstallRequest)(nil),  // 0: gophkeeper.grpc.InstallRequest
	(*InstallResponse)(nil), // 1: gophkeeper.grpc.InstallResponse
}
var file_api_protos_install_proto_depIdxs = []int32{
	0, // 0: gophkeeper.grpc.ClientInstallService.DownloadClient:input_type -> gophkeeper.grpc.InstallRequest
	1, // 1: gophkeeper.grpc.ClientInstallService.DownloadClient:output_type -> gophkeeper.grpc.InstallResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_protos_install_proto_init() }
func file_api_protos_install_proto_init() {
	if File_api_protos_install_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protos_install_proto_rawDesc), len(file_api_protos_install_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protos_install_proto_goTypes,
		DependencyIndexes: file_api_protos_install_proto_depIdxs,
		MessageInfos:      file_api_protos_install_proto_msgTypes,
	}.Build()
	File_api_protos_install_proto = out.File
	file_api_protos_install_proto_goTypes = nil
	file_api_protos_install_proto_depIdxs = nil
}
