// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: secret_binary.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecretBinaryService_List_FullMethodName = "/gophkeeper.SecretBinaryService/List"
	SecretBinaryService_Get_FullMethodName  = "/gophkeeper.SecretBinaryService/Get"
	SecretBinaryService_Save_FullMethodName = "/gophkeeper.SecretBinaryService/Save"
)

// SecretBinaryServiceClient is the client API for SecretBinaryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC-сервис для работы с бинарными секретами
type SecretBinaryServiceClient interface {
	List(ctx context.Context, in *SecretBinaryListRequest, opts ...grpc.CallOption) (*SecretBinaryListResponse, error)
	Get(ctx context.Context, in *SecretBinaryGetRequest, opts ...grpc.CallOption) (*SecretBinaryGetResponse, error)
	Save(ctx context.Context, in *SecretBinarySaveRequest, opts ...grpc.CallOption) (*SecretBinarySaveResponse, error)
}

type secretBinaryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretBinaryServiceClient(cc grpc.ClientConnInterface) SecretBinaryServiceClient {
	return &secretBinaryServiceClient{cc}
}

func (c *secretBinaryServiceClient) List(ctx context.Context, in *SecretBinaryListRequest, opts ...grpc.CallOption) (*SecretBinaryListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretBinaryListResponse)
	err := c.cc.Invoke(ctx, SecretBinaryService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretBinaryServiceClient) Get(ctx context.Context, in *SecretBinaryGetRequest, opts ...grpc.CallOption) (*SecretBinaryGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretBinaryGetResponse)
	err := c.cc.Invoke(ctx, SecretBinaryService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretBinaryServiceClient) Save(ctx context.Context, in *SecretBinarySaveRequest, opts ...grpc.CallOption) (*SecretBinarySaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretBinarySaveResponse)
	err := c.cc.Invoke(ctx, SecretBinaryService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretBinaryServiceServer is the server API for SecretBinaryService service.
// All implementations must embed UnimplementedSecretBinaryServiceServer
// for forward compatibility.
//
// gRPC-сервис для работы с бинарными секретами
type SecretBinaryServiceServer interface {
	List(context.Context, *SecretBinaryListRequest) (*SecretBinaryListResponse, error)
	Get(context.Context, *SecretBinaryGetRequest) (*SecretBinaryGetResponse, error)
	Save(context.Context, *SecretBinarySaveRequest) (*SecretBinarySaveResponse, error)
	mustEmbedUnimplementedSecretBinaryServiceServer()
}

// UnimplementedSecretBinaryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecretBinaryServiceServer struct{}

func (UnimplementedSecretBinaryServiceServer) List(context.Context, *SecretBinaryListRequest) (*SecretBinaryListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSecretBinaryServiceServer) Get(context.Context, *SecretBinaryGetRequest) (*SecretBinaryGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSecretBinaryServiceServer) Save(context.Context, *SecretBinarySaveRequest) (*SecretBinarySaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedSecretBinaryServiceServer) mustEmbedUnimplementedSecretBinaryServiceServer() {}
func (UnimplementedSecretBinaryServiceServer) testEmbeddedByValue()                             {}

// UnsafeSecretBinaryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecretBinaryServiceServer will
// result in compilation errors.
type UnsafeSecretBinaryServiceServer interface {
	mustEmbedUnimplementedSecretBinaryServiceServer()
}

func RegisterSecretBinaryServiceServer(s grpc.ServiceRegistrar, srv SecretBinaryServiceServer) {
	// If the following call pancis, it indicates UnimplementedSecretBinaryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecretBinaryService_ServiceDesc, srv)
}

func _SecretBinaryService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretBinaryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretBinaryServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretBinaryService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretBinaryServiceServer).List(ctx, req.(*SecretBinaryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretBinaryService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretBinaryGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretBinaryServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretBinaryService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretBinaryServiceServer).Get(ctx, req.(*SecretBinaryGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretBinaryService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretBinarySaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretBinaryServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretBinaryService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretBinaryServiceServer).Save(ctx, req.(*SecretBinarySaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecretBinaryService_ServiceDesc is the grpc.ServiceDesc for SecretBinaryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecretBinaryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gophkeeper.SecretBinaryService",
	HandlerType: (*SecretBinaryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _SecretBinaryService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SecretBinaryService_Get_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _SecretBinaryService_Save_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "secret_binary.proto",
}
