// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: secret.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SecretSaveRequest wraps a SecretRequest and token.
type SecretSaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretType    string                 `protobuf:"bytes,2,opt,name=secret_type,json=secretType,proto3" json:"secret_type,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,4,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	AesKeyEnc     []byte                 `protobuf:"bytes,5,opt,name=aes_key_enc,json=aesKeyEnc,proto3" json:"aes_key_enc,omitempty"`
	Token         string                 `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretSaveRequest) Reset() {
	*x = SecretSaveRequest{}
	mi := &file_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretSaveRequest) ProtoMessage() {}

func (x *SecretSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretSaveRequest.ProtoReflect.Descriptor instead.
func (*SecretSaveRequest) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{0}
}

func (x *SecretSaveRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *SecretSaveRequest) GetSecretType() string {
	if x != nil {
		return x.SecretType
	}
	return ""
}

func (x *SecretSaveRequest) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *SecretSaveRequest) GetAesKeyEnc() []byte {
	if x != nil {
		return x.AesKeyEnc
	}
	return nil
}

func (x *SecretSaveRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// SecretSaveRequest defines the request to fetch a secret by its name, type, and token.
type SecretGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretType    string                 `protobuf:"bytes,2,opt,name=secret_type,json=secretType,proto3" json:"secret_type,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretGetRequest) Reset() {
	*x = SecretGetRequest{}
	mi := &file_secret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretGetRequest) ProtoMessage() {}

func (x *SecretGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretGetRequest.ProtoReflect.Descriptor instead.
func (*SecretGetRequest) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{1}
}

func (x *SecretGetRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *SecretGetRequest) GetSecretType() string {
	if x != nil {
		return x.SecretType
	}
	return ""
}

func (x *SecretGetRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// SecretListRequest wraps the token to list all secrets for.
type SecretListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretListRequest) Reset() {
	*x = SecretListRequest{}
	mi := &file_secret_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretListRequest) ProtoMessage() {}

func (x *SecretListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretListRequest.ProtoReflect.Descriptor instead.
func (*SecretListRequest) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{2}
}

func (x *SecretListRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// SecretDB represents a hybrid-encrypted secret stored in DB.
type SecretDB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretType    string                 `protobuf:"bytes,2,opt,name=secret_type,json=secretType,proto3" json:"secret_type,omitempty"`
	SecretOwner   string                 `protobuf:"bytes,3,opt,name=secret_owner,json=secretOwner,proto3" json:"secret_owner,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,4,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	AesKeyEnc     []byte                 `protobuf:"bytes,5,opt,name=aes_key_enc,json=aesKeyEnc,proto3" json:"aes_key_enc,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretDB) Reset() {
	*x = SecretDB{}
	mi := &file_secret_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretDB) ProtoMessage() {}

func (x *SecretDB) ProtoReflect() protoreflect.Message {
	mi := &file_secret_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretDB.ProtoReflect.Descriptor instead.
func (*SecretDB) Descriptor() ([]byte, []int) {
	return file_secret_proto_rawDescGZIP(), []int{3}
}

func (x *SecretDB) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *SecretDB) GetSecretType() string {
	if x != nil {
		return x.SecretType
	}
	return ""
}

func (x *SecretDB) GetSecretOwner() string {
	if x != nil {
		return x.SecretOwner
	}
	return ""
}

func (x *SecretDB) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *SecretDB) GetAesKeyEnc() []byte {
	if x != nil {
		return x.AesKeyEnc
	}
	return nil
}

func (x *SecretDB) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SecretDB) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_secret_proto protoreflect.FileDescriptor

const file_secret_proto_rawDesc = "" +
	"\n" +
	"\fsecret.proto\x12\bbankcard\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x01\n" +
	"\x11SecretSaveRequest\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\x12\x1f\n" +
	"\vsecret_type\x18\x02 \x01(\tR\n" +
	"secretType\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x04 \x01(\fR\n" +
	"ciphertext\x12\x1e\n" +
	"\vaes_key_enc\x18\x05 \x01(\fR\taesKeyEnc\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\"j\n" +
	"\x10SecretGetRequest\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\x12\x1f\n" +
	"\vsecret_type\x18\x02 \x01(\tR\n" +
	"secretType\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\")\n" +
	"\x11SecretListRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xa5\x02\n" +
	"\bSecretDB\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\x12\x1f\n" +
	"\vsecret_type\x18\x02 \x01(\tR\n" +
	"secretType\x12!\n" +
	"\fsecret_owner\x18\x03 \x01(\tR\vsecretOwner\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x04 \x01(\fR\n" +
	"ciphertext\x12\x1e\n" +
	"\vaes_key_enc\x18\x05 \x01(\fR\taesKeyEnc\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2Q\n" +
	"\x12SecretWriteService\x12;\n" +
	"\x04Save\x12\x1b.bankcard.SecretSaveRequest\x1a\x16.google.protobuf.Empty2\x85\x01\n" +
	"\x11SecretReadService\x125\n" +
	"\x03Get\x12\x1a.bankcard.SecretGetRequest\x1a\x12.bankcard.SecretDB\x129\n" +
	"\x04List\x12\x1b.bankcard.SecretListRequest\x1a\x12.bankcard.SecretDB0\x01B-Z+github.com/sbilibin2017/gophkeeper/pkg/grpcb\x06proto3"

var (
	file_secret_proto_rawDescOnce sync.Once
	file_secret_proto_rawDescData []byte
)

func file_secret_proto_rawDescGZIP() []byte {
	file_secret_proto_rawDescOnce.Do(func() {
		file_secret_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_secret_proto_rawDesc), len(file_secret_proto_rawDesc)))
	})
	return file_secret_proto_rawDescData
}

var file_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_secret_proto_goTypes = []any{
	(*SecretSaveRequest)(nil),     // 0: bankcard.SecretSaveRequest
	(*SecretGetRequest)(nil),      // 1: bankcard.SecretGetRequest
	(*SecretListRequest)(nil),     // 2: bankcard.SecretListRequest
	(*SecretDB)(nil),              // 3: bankcard.SecretDB
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_secret_proto_depIdxs = []int32{
	4, // 0: bankcard.SecretDB.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: bankcard.SecretDB.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: bankcard.SecretWriteService.Save:input_type -> bankcard.SecretSaveRequest
	1, // 3: bankcard.SecretReadService.Get:input_type -> bankcard.SecretGetRequest
	2, // 4: bankcard.SecretReadService.List:input_type -> bankcard.SecretListRequest
	5, // 5: bankcard.SecretWriteService.Save:output_type -> google.protobuf.Empty
	3, // 6: bankcard.SecretReadService.Get:output_type -> bankcard.SecretDB
	3, // 7: bankcard.SecretReadService.List:output_type -> bankcard.SecretDB
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_secret_proto_init() }
func file_secret_proto_init() {
	if File_secret_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secret_proto_rawDesc), len(file_secret_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_secret_proto_goTypes,
		DependencyIndexes: file_secret_proto_depIdxs,
		MessageInfos:      file_secret_proto_msgTypes,
	}.Build()
	File_secret_proto = out.File
	file_secret_proto_goTypes = nil
	file_secret_proto_depIdxs = nil
}
