// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: secret_text.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecretTextService_List_FullMethodName = "/gophkeeper.SecretTextService/List"
	SecretTextService_Get_FullMethodName  = "/gophkeeper.SecretTextService/Get"
	SecretTextService_Save_FullMethodName = "/gophkeeper.SecretTextService/Save"
)

// SecretTextServiceClient is the client API for SecretTextService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC-сервис для работы с текстовыми секретами
type SecretTextServiceClient interface {
	List(ctx context.Context, in *SecretTextListRequest, opts ...grpc.CallOption) (*SecretTextListResponse, error)
	Get(ctx context.Context, in *SecretTextGetRequest, opts ...grpc.CallOption) (*SecretTextGetResponse, error)
	Save(ctx context.Context, in *SecretTextSaveRequest, opts ...grpc.CallOption) (*SecretTextSaveResponse, error)
}

type secretTextServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretTextServiceClient(cc grpc.ClientConnInterface) SecretTextServiceClient {
	return &secretTextServiceClient{cc}
}

func (c *secretTextServiceClient) List(ctx context.Context, in *SecretTextListRequest, opts ...grpc.CallOption) (*SecretTextListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretTextListResponse)
	err := c.cc.Invoke(ctx, SecretTextService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretTextServiceClient) Get(ctx context.Context, in *SecretTextGetRequest, opts ...grpc.CallOption) (*SecretTextGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretTextGetResponse)
	err := c.cc.Invoke(ctx, SecretTextService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretTextServiceClient) Save(ctx context.Context, in *SecretTextSaveRequest, opts ...grpc.CallOption) (*SecretTextSaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretTextSaveResponse)
	err := c.cc.Invoke(ctx, SecretTextService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretTextServiceServer is the server API for SecretTextService service.
// All implementations must embed UnimplementedSecretTextServiceServer
// for forward compatibility.
//
// gRPC-сервис для работы с текстовыми секретами
type SecretTextServiceServer interface {
	List(context.Context, *SecretTextListRequest) (*SecretTextListResponse, error)
	Get(context.Context, *SecretTextGetRequest) (*SecretTextGetResponse, error)
	Save(context.Context, *SecretTextSaveRequest) (*SecretTextSaveResponse, error)
	mustEmbedUnimplementedSecretTextServiceServer()
}

// UnimplementedSecretTextServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecretTextServiceServer struct{}

func (UnimplementedSecretTextServiceServer) List(context.Context, *SecretTextListRequest) (*SecretTextListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSecretTextServiceServer) Get(context.Context, *SecretTextGetRequest) (*SecretTextGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSecretTextServiceServer) Save(context.Context, *SecretTextSaveRequest) (*SecretTextSaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedSecretTextServiceServer) mustEmbedUnimplementedSecretTextServiceServer() {}
func (UnimplementedSecretTextServiceServer) testEmbeddedByValue()                           {}

// UnsafeSecretTextServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecretTextServiceServer will
// result in compilation errors.
type UnsafeSecretTextServiceServer interface {
	mustEmbedUnimplementedSecretTextServiceServer()
}

func RegisterSecretTextServiceServer(s grpc.ServiceRegistrar, srv SecretTextServiceServer) {
	// If the following call pancis, it indicates UnimplementedSecretTextServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecretTextService_ServiceDesc, srv)
}

func _SecretTextService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretTextListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretTextServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretTextService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretTextServiceServer).List(ctx, req.(*SecretTextListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretTextService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretTextGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretTextServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretTextService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretTextServiceServer).Get(ctx, req.(*SecretTextGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretTextService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretTextSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretTextServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretTextService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretTextServiceServer).Save(ctx, req.(*SecretTextSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecretTextService_ServiceDesc is the grpc.ServiceDesc for SecretTextService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecretTextService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gophkeeper.SecretTextService",
	HandlerType: (*SecretTextServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _SecretTextService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SecretTextService_Get_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _SecretTextService_Save_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "secret_text.proto",
}
