// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: secret_text.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на сохранение текстового секрета
type SecretTextSaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"` // Уникальное имя секрета
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                         // Текстовое содержимое секрета
	Meta          string                 `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`                               // Дополнительные метаданные (может быть пустым)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretTextSaveRequest) Reset() {
	*x = SecretTextSaveRequest{}
	mi := &file_secret_text_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretTextSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretTextSaveRequest) ProtoMessage() {}

func (x *SecretTextSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_text_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretTextSaveRequest.ProtoReflect.Descriptor instead.
func (*SecretTextSaveRequest) Descriptor() ([]byte, []int) {
	return file_secret_text_proto_rawDescGZIP(), []int{0}
}

func (x *SecretTextSaveRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *SecretTextSaveRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SecretTextSaveRequest) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

// Ответ на сохранение (пустой)
type SecretTextSaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretTextSaveResponse) Reset() {
	*x = SecretTextSaveResponse{}
	mi := &file_secret_text_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretTextSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretTextSaveResponse) ProtoMessage() {}

func (x *SecretTextSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_text_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretTextSaveResponse.ProtoReflect.Descriptor instead.
func (*SecretTextSaveResponse) Descriptor() ([]byte, []int) {
	return file_secret_text_proto_rawDescGZIP(), []int{1}
}

// Запрос на получение одного текстового секрета по имени
type SecretTextGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretTextGetRequest) Reset() {
	*x = SecretTextGetRequest{}
	mi := &file_secret_text_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretTextGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretTextGetRequest) ProtoMessage() {}

func (x *SecretTextGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_text_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretTextGetRequest.ProtoReflect.Descriptor instead.
func (*SecretTextGetRequest) Descriptor() ([]byte, []int) {
	return file_secret_text_proto_rawDescGZIP(), []int{2}
}

func (x *SecretTextGetRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

// Ответ на получение одного текстового секрета
type SecretTextGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretOwner   string                 `protobuf:"bytes,2,opt,name=secret_owner,json=secretOwner,proto3" json:"secret_owner,omitempty"` // Владелец секрета
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Meta          string                 `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretTextGetResponse) Reset() {
	*x = SecretTextGetResponse{}
	mi := &file_secret_text_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretTextGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretTextGetResponse) ProtoMessage() {}

func (x *SecretTextGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_text_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretTextGetResponse.ProtoReflect.Descriptor instead.
func (*SecretTextGetResponse) Descriptor() ([]byte, []int) {
	return file_secret_text_proto_rawDescGZIP(), []int{3}
}

func (x *SecretTextGetResponse) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *SecretTextGetResponse) GetSecretOwner() string {
	if x != nil {
		return x.SecretOwner
	}
	return ""
}

func (x *SecretTextGetResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SecretTextGetResponse) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *SecretTextGetResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Запрос на получение списка текстовых секретов
type SecretTextListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretTextListRequest) Reset() {
	*x = SecretTextListRequest{}
	mi := &file_secret_text_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretTextListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretTextListRequest) ProtoMessage() {}

func (x *SecretTextListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_text_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretTextListRequest.ProtoReflect.Descriptor instead.
func (*SecretTextListRequest) Descriptor() ([]byte, []int) {
	return file_secret_text_proto_rawDescGZIP(), []int{4}
}

// Ответ со списком текстовых секретов
type SecretTextListResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Items         []*SecretTextGetResponse `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretTextListResponse) Reset() {
	*x = SecretTextListResponse{}
	mi := &file_secret_text_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretTextListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretTextListResponse) ProtoMessage() {}

func (x *SecretTextListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_text_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretTextListResponse.ProtoReflect.Descriptor instead.
func (*SecretTextListResponse) Descriptor() ([]byte, []int) {
	return file_secret_text_proto_rawDescGZIP(), []int{5}
}

func (x *SecretTextListResponse) GetItems() []*SecretTextGetResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_secret_text_proto protoreflect.FileDescriptor

const file_secret_text_proto_rawDesc = "" +
	"\n" +
	"\x11secret_text.proto\x12\n" +
	"gophkeeper\"f\n" +
	"\x15SecretTextSaveRequest\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04meta\x18\x03 \x01(\tR\x04meta\"\x18\n" +
	"\x16SecretTextSaveResponse\"7\n" +
	"\x14SecretTextGetRequest\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\"\xa8\x01\n" +
	"\x15SecretTextGetResponse\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\x12!\n" +
	"\fsecret_owner\x18\x02 \x01(\tR\vsecretOwner\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04meta\x18\x04 \x01(\tR\x04meta\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"\x17\n" +
	"\x15SecretTextListRequest\"Q\n" +
	"\x16SecretTextListResponse\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.gophkeeper.SecretTextGetResponseR\x05items2\xfd\x01\n" +
	"\x11SecretTextService\x12M\n" +
	"\x04List\x12!.gophkeeper.SecretTextListRequest\x1a\".gophkeeper.SecretTextListResponse\x12J\n" +
	"\x03Get\x12 .gophkeeper.SecretTextGetRequest\x1a!.gophkeeper.SecretTextGetResponse\x12M\n" +
	"\x04Save\x12!.gophkeeper.SecretTextSaveRequest\x1a\".gophkeeper.SecretTextSaveResponseB\n" +
	"Z\bpkg/grpcb\x06proto3"

var (
	file_secret_text_proto_rawDescOnce sync.Once
	file_secret_text_proto_rawDescData []byte
)

func file_secret_text_proto_rawDescGZIP() []byte {
	file_secret_text_proto_rawDescOnce.Do(func() {
		file_secret_text_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_secret_text_proto_rawDesc), len(file_secret_text_proto_rawDesc)))
	})
	return file_secret_text_proto_rawDescData
}

var file_secret_text_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_secret_text_proto_goTypes = []any{
	(*SecretTextSaveRequest)(nil),  // 0: gophkeeper.SecretTextSaveRequest
	(*SecretTextSaveResponse)(nil), // 1: gophkeeper.SecretTextSaveResponse
	(*SecretTextGetRequest)(nil),   // 2: gophkeeper.SecretTextGetRequest
	(*SecretTextGetResponse)(nil),  // 3: gophkeeper.SecretTextGetResponse
	(*SecretTextListRequest)(nil),  // 4: gophkeeper.SecretTextListRequest
	(*SecretTextListResponse)(nil), // 5: gophkeeper.SecretTextListResponse
}
var file_secret_text_proto_depIdxs = []int32{
	3, // 0: gophkeeper.SecretTextListResponse.items:type_name -> gophkeeper.SecretTextGetResponse
	4, // 1: gophkeeper.SecretTextService.List:input_type -> gophkeeper.SecretTextListRequest
	2, // 2: gophkeeper.SecretTextService.Get:input_type -> gophkeeper.SecretTextGetRequest
	0, // 3: gophkeeper.SecretTextService.Save:input_type -> gophkeeper.SecretTextSaveRequest
	5, // 4: gophkeeper.SecretTextService.List:output_type -> gophkeeper.SecretTextListResponse
	3, // 5: gophkeeper.SecretTextService.Get:output_type -> gophkeeper.SecretTextGetResponse
	1, // 6: gophkeeper.SecretTextService.Save:output_type -> gophkeeper.SecretTextSaveResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_secret_text_proto_init() }
func file_secret_text_proto_init() {
	if File_secret_text_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secret_text_proto_rawDesc), len(file_secret_text_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_secret_text_proto_goTypes,
		DependencyIndexes: file_secret_text_proto_depIdxs,
		MessageInfos:      file_secret_text_proto_msgTypes,
	}.Build()
	File_secret_text_proto = out.File
	file_secret_text_proto_goTypes = nil
	file_secret_text_proto_depIdxs = nil
}
