// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: secret_binary.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Представление бинарного секрета
type SecretBinary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Meta          string                 `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretBinary) Reset() {
	*x = SecretBinary{}
	mi := &file_secret_binary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretBinary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretBinary) ProtoMessage() {}

func (x *SecretBinary) ProtoReflect() protoreflect.Message {
	mi := &file_secret_binary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretBinary.ProtoReflect.Descriptor instead.
func (*SecretBinary) Descriptor() ([]byte, []int) {
	return file_secret_binary_proto_rawDescGZIP(), []int{0}
}

func (x *SecretBinary) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *SecretBinary) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SecretBinary) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *SecretBinary) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Запрос списка бинарных секретов
type SecretBinaryListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretBinaryListRequest) Reset() {
	*x = SecretBinaryListRequest{}
	mi := &file_secret_binary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretBinaryListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretBinaryListRequest) ProtoMessage() {}

func (x *SecretBinaryListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_secret_binary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretBinaryListRequest.ProtoReflect.Descriptor instead.
func (*SecretBinaryListRequest) Descriptor() ([]byte, []int) {
	return file_secret_binary_proto_rawDescGZIP(), []int{1}
}

func (x *SecretBinaryListRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Ответ со списком бинарных секретов
type SecretBinaryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SecretBinary        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretBinaryListResponse) Reset() {
	*x = SecretBinaryListResponse{}
	mi := &file_secret_binary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretBinaryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretBinaryListResponse) ProtoMessage() {}

func (x *SecretBinaryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_secret_binary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretBinaryListResponse.ProtoReflect.Descriptor instead.
func (*SecretBinaryListResponse) Descriptor() ([]byte, []int) {
	return file_secret_binary_proto_rawDescGZIP(), []int{2}
}

func (x *SecretBinaryListResponse) GetItems() []*SecretBinary {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_secret_binary_proto protoreflect.FileDescriptor

const file_secret_binary_proto_rawDesc = "" +
	"\n" +
	"\x13secret_binary.proto\x12\n" +
	"gophkeeper\"v\n" +
	"\fSecretBinary\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04meta\x18\x03 \x01(\tR\x04meta\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\"/\n" +
	"\x17SecretBinaryListRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"J\n" +
	"\x18SecretBinaryListResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.gophkeeper.SecretBinaryR\x05items2u\n" +
	"\x13SecretBinaryService\x12^\n" +
	"\x11ListBinarySecrets\x12#.gophkeeper.SecretBinaryListRequest\x1a$.gophkeeper.SecretBinaryListResponseB\n" +
	"Z\bpkg/grpcb\x06proto3"

var (
	file_secret_binary_proto_rawDescOnce sync.Once
	file_secret_binary_proto_rawDescData []byte
)

func file_secret_binary_proto_rawDescGZIP() []byte {
	file_secret_binary_proto_rawDescOnce.Do(func() {
		file_secret_binary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_secret_binary_proto_rawDesc), len(file_secret_binary_proto_rawDesc)))
	})
	return file_secret_binary_proto_rawDescData
}

var file_secret_binary_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_secret_binary_proto_goTypes = []any{
	(*SecretBinary)(nil),             // 0: gophkeeper.SecretBinary
	(*SecretBinaryListRequest)(nil),  // 1: gophkeeper.SecretBinaryListRequest
	(*SecretBinaryListResponse)(nil), // 2: gophkeeper.SecretBinaryListResponse
}
var file_secret_binary_proto_depIdxs = []int32{
	0, // 0: gophkeeper.SecretBinaryListResponse.items:type_name -> gophkeeper.SecretBinary
	1, // 1: gophkeeper.SecretBinaryService.ListBinarySecrets:input_type -> gophkeeper.SecretBinaryListRequest
	2, // 2: gophkeeper.SecretBinaryService.ListBinarySecrets:output_type -> gophkeeper.SecretBinaryListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_secret_binary_proto_init() }
func file_secret_binary_proto_init() {
	if File_secret_binary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_secret_binary_proto_rawDesc), len(file_secret_binary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_secret_binary_proto_goTypes,
		DependencyIndexes: file_secret_binary_proto_depIdxs,
		MessageInfos:      file_secret_binary_proto_msgTypes,
	}.Build()
	File_secret_binary_proto = out.File
	file_secret_binary_proto_goTypes = nil
	file_secret_binary_proto_depIdxs = nil
}
