// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: text.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Meta          string                 `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextAddRequest) Reset() {
	*x = TextAddRequest{}
	mi := &file_text_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextAddRequest) ProtoMessage() {}

func (x *TextAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_text_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextAddRequest.ProtoReflect.Descriptor instead.
func (*TextAddRequest) Descriptor() ([]byte, []int) {
	return file_text_proto_rawDescGZIP(), []int{0}
}

func (x *TextAddRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *TextAddRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TextAddRequest) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type TextGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextGetRequest) Reset() {
	*x = TextGetRequest{}
	mi := &file_text_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextGetRequest) ProtoMessage() {}

func (x *TextGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_text_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextGetRequest.ProtoReflect.Descriptor instead.
func (*TextGetRequest) Descriptor() ([]byte, []int) {
	return file_text_proto_rawDescGZIP(), []int{1}
}

func (x *TextGetRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

type TextGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretOwner   string                 `protobuf:"bytes,2,opt,name=secret_owner,json=secretOwner,proto3" json:"secret_owner,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Meta          string                 `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextGetResponse) Reset() {
	*x = TextGetResponse{}
	mi := &file_text_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextGetResponse) ProtoMessage() {}

func (x *TextGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_text_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextGetResponse.ProtoReflect.Descriptor instead.
func (*TextGetResponse) Descriptor() ([]byte, []int) {
	return file_text_proto_rawDescGZIP(), []int{2}
}

func (x *TextGetResponse) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *TextGetResponse) GetSecretOwner() string {
	if x != nil {
		return x.SecretOwner
	}
	return ""
}

func (x *TextGetResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TextGetResponse) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *TextGetResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type TextListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TextGetResponse     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextListResponse) Reset() {
	*x = TextListResponse{}
	mi := &file_text_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextListResponse) ProtoMessage() {}

func (x *TextListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_text_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextListResponse.ProtoReflect.Descriptor instead.
func (*TextListResponse) Descriptor() ([]byte, []int) {
	return file_text_proto_rawDescGZIP(), []int{3}
}

func (x *TextListResponse) GetItems() []*TextGetResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_text_proto protoreflect.FileDescriptor

const file_text_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"text.proto\x12\x04text\x1a\x1bgoogle/protobuf/empty.proto\"_\n" +
	"\x0eTextAddRequest\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04meta\x18\x03 \x01(\tR\x04meta\"1\n" +
	"\x0eTextGetRequest\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\"\xa2\x01\n" +
	"\x0fTextGetResponse\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\x12!\n" +
	"\fsecret_owner\x18\x02 \x01(\tR\vsecretOwner\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04meta\x18\x04 \x01(\tR\x04meta\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"?\n" +
	"\x10TextListResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.text.TextGetResponseR\x05items2E\n" +
	"\x0eTextAddService\x123\n" +
	"\x03Add\x12\x14.text.TextAddRequest\x1a\x16.google.protobuf.Empty2D\n" +
	"\x0eTextGetService\x122\n" +
	"\x03Get\x12\x14.text.TextGetRequest\x1a\x15.text.TextGetResponse2I\n" +
	"\x0fTextListService\x126\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\x16.text.TextListResponseB-Z+github.com/sbilibin2017/gophkeeper/pkg/grpcb\x06proto3"

var (
	file_text_proto_rawDescOnce sync.Once
	file_text_proto_rawDescData []byte
)

func file_text_proto_rawDescGZIP() []byte {
	file_text_proto_rawDescOnce.Do(func() {
		file_text_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_text_proto_rawDesc), len(file_text_proto_rawDesc)))
	})
	return file_text_proto_rawDescData
}

var file_text_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_text_proto_goTypes = []any{
	(*TextAddRequest)(nil),   // 0: text.TextAddRequest
	(*TextGetRequest)(nil),   // 1: text.TextGetRequest
	(*TextGetResponse)(nil),  // 2: text.TextGetResponse
	(*TextListResponse)(nil), // 3: text.TextListResponse
	(*emptypb.Empty)(nil),    // 4: google.protobuf.Empty
}
var file_text_proto_depIdxs = []int32{
	2, // 0: text.TextListResponse.items:type_name -> text.TextGetResponse
	0, // 1: text.TextAddService.Add:input_type -> text.TextAddRequest
	1, // 2: text.TextGetService.Get:input_type -> text.TextGetRequest
	4, // 3: text.TextListService.List:input_type -> google.protobuf.Empty
	4, // 4: text.TextAddService.Add:output_type -> google.protobuf.Empty
	2, // 5: text.TextGetService.Get:output_type -> text.TextGetResponse
	3, // 6: text.TextListService.List:output_type -> text.TextListResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_text_proto_init() }
func file_text_proto_init() {
	if File_text_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_text_proto_rawDesc), len(file_text_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_text_proto_goTypes,
		DependencyIndexes: file_text_proto_depIdxs,
		MessageInfos:      file_text_proto_msgTypes,
	}.Build()
	File_text_proto = out.File
	file_text_proto_goTypes = nil
	file_text_proto_depIdxs = nil
}
