// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: text.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,3,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextAddRequest) Reset() {
	*x = TextAddRequest{}
	mi := &file_text_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextAddRequest) ProtoMessage() {}

func (x *TextAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_text_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextAddRequest.ProtoReflect.Descriptor instead.
func (*TextAddRequest) Descriptor() ([]byte, []int) {
	return file_text_proto_rawDescGZIP(), []int{0}
}

func (x *TextAddRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *TextAddRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TextAddRequest) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type TextFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextFilterRequest) Reset() {
	*x = TextFilterRequest{}
	mi := &file_text_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextFilterRequest) ProtoMessage() {}

func (x *TextFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_text_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextFilterRequest.ProtoReflect.Descriptor instead.
func (*TextFilterRequest) Descriptor() ([]byte, []int) {
	return file_text_proto_rawDescGZIP(), []int{1}
}

func (x *TextFilterRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

type TextDB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretOwner   string                 `protobuf:"bytes,2,opt,name=secret_owner,json=secretOwner,proto3" json:"secret_owner,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,4,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextDB) Reset() {
	*x = TextDB{}
	mi := &file_text_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextDB) ProtoMessage() {}

func (x *TextDB) ProtoReflect() protoreflect.Message {
	mi := &file_text_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextDB.ProtoReflect.Descriptor instead.
func (*TextDB) Descriptor() ([]byte, []int) {
	return file_text_proto_rawDescGZIP(), []int{2}
}

func (x *TextDB) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *TextDB) GetSecretOwner() string {
	if x != nil {
		return x.SecretOwner
	}
	return ""
}

func (x *TextDB) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TextDB) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *TextDB) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_text_proto protoreflect.FileDescriptor

const file_text_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"text.proto\x12\x04text\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb8\x01\n" +
	"\x0eTextAddRequest\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x122\n" +
	"\x04meta\x18\x03 \x03(\v2\x1e.text.TextAddRequest.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x11TextFilterRequest\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\"\x86\x02\n" +
	"\x06TextDB\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\x12!\n" +
	"\fsecret_owner\x18\x02 \x01(\tR\vsecretOwner\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12*\n" +
	"\x04meta\x18\x04 \x03(\v2\x16.text.TextDB.MetaEntryR\x04meta\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xa0\x01\n" +
	"\vTextService\x123\n" +
	"\x03Add\x12\x14.text.TextAddRequest\x1a\x16.google.protobuf.Empty\x12,\n" +
	"\x03Get\x12\x17.text.TextFilterRequest\x1a\f.text.TextDB\x12.\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\f.text.TextDB0\x01B-Z+github.com/sbilibin2017/gophkeeper/pkg/grpcb\x06proto3"

var (
	file_text_proto_rawDescOnce sync.Once
	file_text_proto_rawDescData []byte
)

func file_text_proto_rawDescGZIP() []byte {
	file_text_proto_rawDescOnce.Do(func() {
		file_text_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_text_proto_rawDesc), len(file_text_proto_rawDesc)))
	})
	return file_text_proto_rawDescData
}

var file_text_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_text_proto_goTypes = []any{
	(*TextAddRequest)(nil),        // 0: text.TextAddRequest
	(*TextFilterRequest)(nil),     // 1: text.TextFilterRequest
	(*TextDB)(nil),                // 2: text.TextDB
	nil,                           // 3: text.TextAddRequest.MetaEntry
	nil,                           // 4: text.TextDB.MetaEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_text_proto_depIdxs = []int32{
	3, // 0: text.TextAddRequest.meta:type_name -> text.TextAddRequest.MetaEntry
	4, // 1: text.TextDB.meta:type_name -> text.TextDB.MetaEntry
	5, // 2: text.TextDB.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: text.TextService.Add:input_type -> text.TextAddRequest
	1, // 4: text.TextService.Get:input_type -> text.TextFilterRequest
	6, // 5: text.TextService.List:input_type -> google.protobuf.Empty
	6, // 6: text.TextService.Add:output_type -> google.protobuf.Empty
	2, // 7: text.TextService.Get:output_type -> text.TextDB
	2, // 8: text.TextService.List:output_type -> text.TextDB
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_text_proto_init() }
func file_text_proto_init() {
	if File_text_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_text_proto_rawDesc), len(file_text_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_text_proto_goTypes,
		DependencyIndexes: file_text_proto_depIdxs,
		MessageInfos:      file_text_proto_msgTypes,
	}.Build()
	File_text_proto = out.File
	file_text_proto_goTypes = nil
	file_text_proto_depIdxs = nil
}
