// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: username_password.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UsernamePasswordAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Meta          string                 `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsernamePasswordAddRequest) Reset() {
	*x = UsernamePasswordAddRequest{}
	mi := &file_username_password_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsernamePasswordAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsernamePasswordAddRequest) ProtoMessage() {}

func (x *UsernamePasswordAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_username_password_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsernamePasswordAddRequest.ProtoReflect.Descriptor instead.
func (*UsernamePasswordAddRequest) Descriptor() ([]byte, []int) {
	return file_username_password_proto_rawDescGZIP(), []int{0}
}

func (x *UsernamePasswordAddRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *UsernamePasswordAddRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UsernamePasswordAddRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UsernamePasswordAddRequest) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type UsernamePasswordGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsernamePasswordGetRequest) Reset() {
	*x = UsernamePasswordGetRequest{}
	mi := &file_username_password_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsernamePasswordGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsernamePasswordGetRequest) ProtoMessage() {}

func (x *UsernamePasswordGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_username_password_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsernamePasswordGetRequest.ProtoReflect.Descriptor instead.
func (*UsernamePasswordGetRequest) Descriptor() ([]byte, []int) {
	return file_username_password_proto_rawDescGZIP(), []int{1}
}

func (x *UsernamePasswordGetRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

type UsernamePasswordGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretOwner   string                 `protobuf:"bytes,2,opt,name=secret_owner,json=secretOwner,proto3" json:"secret_owner,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Meta          string                 `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsernamePasswordGetResponse) Reset() {
	*x = UsernamePasswordGetResponse{}
	mi := &file_username_password_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsernamePasswordGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsernamePasswordGetResponse) ProtoMessage() {}

func (x *UsernamePasswordGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_username_password_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsernamePasswordGetResponse.ProtoReflect.Descriptor instead.
func (*UsernamePasswordGetResponse) Descriptor() ([]byte, []int) {
	return file_username_password_proto_rawDescGZIP(), []int{2}
}

func (x *UsernamePasswordGetResponse) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *UsernamePasswordGetResponse) GetSecretOwner() string {
	if x != nil {
		return x.SecretOwner
	}
	return ""
}

func (x *UsernamePasswordGetResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UsernamePasswordGetResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UsernamePasswordGetResponse) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *UsernamePasswordGetResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type UsernamePasswordListResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Items         []*UsernamePasswordGetResponse `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsernamePasswordListResponse) Reset() {
	*x = UsernamePasswordListResponse{}
	mi := &file_username_password_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsernamePasswordListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsernamePasswordListResponse) ProtoMessage() {}

func (x *UsernamePasswordListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_username_password_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsernamePasswordListResponse.ProtoReflect.Descriptor instead.
func (*UsernamePasswordListResponse) Descriptor() ([]byte, []int) {
	return file_username_password_proto_rawDescGZIP(), []int{3}
}

func (x *UsernamePasswordListResponse) GetItems() []*UsernamePasswordGetResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

type UsernamePasswordDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsernamePasswordDeleteRequest) Reset() {
	*x = UsernamePasswordDeleteRequest{}
	mi := &file_username_password_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsernamePasswordDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsernamePasswordDeleteRequest) ProtoMessage() {}

func (x *UsernamePasswordDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_username_password_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsernamePasswordDeleteRequest.ProtoReflect.Descriptor instead.
func (*UsernamePasswordDeleteRequest) Descriptor() ([]byte, []int) {
	return file_username_password_proto_rawDescGZIP(), []int{4}
}

func (x *UsernamePasswordDeleteRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

var File_username_password_proto protoreflect.FileDescriptor

const file_username_password_proto_rawDesc = "" +
	"\n" +
	"\x17username_password.proto\x12\x11username_password\x1a\x1bgoogle/protobuf/empty.proto\"\x89\x01\n" +
	"\x1aUsernamePasswordAddRequest\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04meta\x18\x04 \x01(\tR\x04meta\"=\n" +
	"\x1aUsernamePasswordGetRequest\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\"\xcc\x01\n" +
	"\x1bUsernamePasswordGetResponse\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\x12!\n" +
	"\fsecret_owner\x18\x02 \x01(\tR\vsecretOwner\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x12\n" +
	"\x04meta\x18\x05 \x01(\tR\x04meta\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"d\n" +
	"\x1cUsernamePasswordListResponse\x12D\n" +
	"\x05items\x18\x01 \x03(\v2..username_password.UsernamePasswordGetResponseR\x05items\"@\n" +
	"\x1dUsernamePasswordDeleteRequest\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName2j\n" +
	"\x1aUsernamePasswordAddService\x12L\n" +
	"\x03Add\x12-.username_password.UsernamePasswordAddRequest\x1a\x16.google.protobuf.Empty2\x82\x01\n" +
	"\x1aUsernamePasswordGetService\x12d\n" +
	"\x03Get\x12-.username_password.UsernamePasswordGetRequest\x1a..username_password.UsernamePasswordGetResponse2n\n" +
	"\x1bUsernamePasswordListService\x12O\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a/.username_password.UsernamePasswordListResponse2s\n" +
	"\x1dUsernamePasswordDeleteService\x12R\n" +
	"\x06Delete\x120.username_password.UsernamePasswordDeleteRequest\x1a\x16.google.protobuf.EmptyB-Z+github.com/sbilibin2017/gophkeeper/pkg/grpcb\x06proto3"

var (
	file_username_password_proto_rawDescOnce sync.Once
	file_username_password_proto_rawDescData []byte
)

func file_username_password_proto_rawDescGZIP() []byte {
	file_username_password_proto_rawDescOnce.Do(func() {
		file_username_password_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_username_password_proto_rawDesc), len(file_username_password_proto_rawDesc)))
	})
	return file_username_password_proto_rawDescData
}

var file_username_password_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_username_password_proto_goTypes = []any{
	(*UsernamePasswordAddRequest)(nil),    // 0: username_password.UsernamePasswordAddRequest
	(*UsernamePasswordGetRequest)(nil),    // 1: username_password.UsernamePasswordGetRequest
	(*UsernamePasswordGetResponse)(nil),   // 2: username_password.UsernamePasswordGetResponse
	(*UsernamePasswordListResponse)(nil),  // 3: username_password.UsernamePasswordListResponse
	(*UsernamePasswordDeleteRequest)(nil), // 4: username_password.UsernamePasswordDeleteRequest
	(*emptypb.Empty)(nil),                 // 5: google.protobuf.Empty
}
var file_username_password_proto_depIdxs = []int32{
	2, // 0: username_password.UsernamePasswordListResponse.items:type_name -> username_password.UsernamePasswordGetResponse
	0, // 1: username_password.UsernamePasswordAddService.Add:input_type -> username_password.UsernamePasswordAddRequest
	1, // 2: username_password.UsernamePasswordGetService.Get:input_type -> username_password.UsernamePasswordGetRequest
	5, // 3: username_password.UsernamePasswordListService.List:input_type -> google.protobuf.Empty
	4, // 4: username_password.UsernamePasswordDeleteService.Delete:input_type -> username_password.UsernamePasswordDeleteRequest
	5, // 5: username_password.UsernamePasswordAddService.Add:output_type -> google.protobuf.Empty
	2, // 6: username_password.UsernamePasswordGetService.Get:output_type -> username_password.UsernamePasswordGetResponse
	3, // 7: username_password.UsernamePasswordListService.List:output_type -> username_password.UsernamePasswordListResponse
	5, // 8: username_password.UsernamePasswordDeleteService.Delete:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_username_password_proto_init() }
func file_username_password_proto_init() {
	if File_username_password_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_username_password_proto_rawDesc), len(file_username_password_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_username_password_proto_goTypes,
		DependencyIndexes: file_username_password_proto_depIdxs,
		MessageInfos:      file_username_password_proto_msgTypes,
	}.Build()
	File_username_password_proto = out.File
	file_username_password_proto_goTypes = nil
	file_username_password_proto_depIdxs = nil
}
