// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: user.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,4,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAddRequest) Reset() {
	*x = UserAddRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAddRequest) ProtoMessage() {}

func (x *UserAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAddRequest.ProtoReflect.Descriptor instead.
func (*UserAddRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserAddRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *UserAddRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserAddRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserAddRequest) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type UserFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFilterRequest) Reset() {
	*x = UserFilterRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFilterRequest) ProtoMessage() {}

func (x *UserFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFilterRequest.ProtoReflect.Descriptor instead.
func (*UserFilterRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserFilterRequest) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

type UserDB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretName    string                 `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	SecretOwner   string                 `protobuf:"bytes,2,opt,name=secret_owner,json=secretOwner,proto3" json:"secret_owner,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,5,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDB) Reset() {
	*x = UserDB{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDB) ProtoMessage() {}

func (x *UserDB) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDB.ProtoReflect.Descriptor instead.
func (*UserDB) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserDB) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *UserDB) GetSecretOwner() string {
	if x != nil {
		return x.SecretOwner
	}
	return ""
}

func (x *UserDB) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserDB) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserDB) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *UserDB) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd6\x01\n" +
	"\x0eUserAddRequest\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x122\n" +
	"\x04meta\x18\x04 \x03(\v2\x1e.user.UserAddRequest.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x11UserFilterRequest\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\"\xa4\x02\n" +
	"\x06UserDB\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\x12!\n" +
	"\fsecret_owner\x18\x02 \x01(\tR\vsecretOwner\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12*\n" +
	"\x04meta\x18\x05 \x03(\v2\x16.user.UserDB.MetaEntryR\x04meta\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xa0\x01\n" +
	"\vUserService\x123\n" +
	"\x03Add\x12\x14.user.UserAddRequest\x1a\x16.google.protobuf.Empty\x12,\n" +
	"\x03Get\x12\x17.user.UserFilterRequest\x1a\f.user.UserDB\x12.\n" +
	"\x04List\x12\x16.google.protobuf.Empty\x1a\f.user.UserDB0\x01B-Z+github.com/sbilibin2017/gophkeeper/pkg/grpcb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_proto_goTypes = []any{
	(*UserAddRequest)(nil),        // 0: user.UserAddRequest
	(*UserFilterRequest)(nil),     // 1: user.UserFilterRequest
	(*UserDB)(nil),                // 2: user.UserDB
	nil,                           // 3: user.UserAddRequest.MetaEntry
	nil,                           // 4: user.UserDB.MetaEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_user_proto_depIdxs = []int32{
	3, // 0: user.UserAddRequest.meta:type_name -> user.UserAddRequest.MetaEntry
	4, // 1: user.UserDB.meta:type_name -> user.UserDB.MetaEntry
	5, // 2: user.UserDB.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: user.UserService.Add:input_type -> user.UserAddRequest
	1, // 4: user.UserService.Get:input_type -> user.UserFilterRequest
	6, // 5: user.UserService.List:input_type -> google.protobuf.Empty
	6, // 6: user.UserService.Add:output_type -> google.protobuf.Empty
	2, // 7: user.UserService.Get:output_type -> user.UserDB
	2, // 8: user.UserService.List:output_type -> user.UserDB
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
