// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Github/gophkeeper/internal/handlers/grpc/secret.go

// Package grpc is a generated GoMock package.
package grpc

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/sbilibin2017/gophkeeper/internal/models"
)

// MockSecretWriter is a mock of SecretWriter interface.
type MockSecretWriter struct {
	ctrl     *gomock.Controller
	recorder *MockSecretWriterMockRecorder
}

// MockSecretWriterMockRecorder is the mock recorder for MockSecretWriter.
type MockSecretWriterMockRecorder struct {
	mock *MockSecretWriter
}

// NewMockSecretWriter creates a new mock instance.
func NewMockSecretWriter(ctrl *gomock.Controller) *MockSecretWriter {
	mock := &MockSecretWriter{ctrl: ctrl}
	mock.recorder = &MockSecretWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretWriter) EXPECT() *MockSecretWriterMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockSecretWriter) Save(ctx context.Context, secretOwner, secretName, secretType string, ciphertext, aesKeyEnc []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, secretOwner, secretName, secretType, ciphertext, aesKeyEnc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSecretWriterMockRecorder) Save(ctx, secretOwner, secretName, secretType, ciphertext, aesKeyEnc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSecretWriter)(nil).Save), ctx, secretOwner, secretName, secretType, ciphertext, aesKeyEnc)
}

// MockSecretReader is a mock of SecretReader interface.
type MockSecretReader struct {
	ctrl     *gomock.Controller
	recorder *MockSecretReaderMockRecorder
}

// MockSecretReaderMockRecorder is the mock recorder for MockSecretReader.
type MockSecretReaderMockRecorder struct {
	mock *MockSecretReader
}

// NewMockSecretReader creates a new mock instance.
func NewMockSecretReader(ctrl *gomock.Controller) *MockSecretReader {
	mock := &MockSecretReader{ctrl: ctrl}
	mock.recorder = &MockSecretReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretReader) EXPECT() *MockSecretReaderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSecretReader) Get(ctx context.Context, secretOwner, secretType, secretName string) (*models.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, secretOwner, secretType, secretName)
	ret0, _ := ret[0].(*models.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSecretReaderMockRecorder) Get(ctx, secretOwner, secretType, secretName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSecretReader)(nil).Get), ctx, secretOwner, secretType, secretName)
}

// List mocks base method.
func (m *MockSecretReader) List(ctx context.Context, secretOwner string) ([]*models.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, secretOwner)
	ret0, _ := ret[0].([]*models.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSecretReaderMockRecorder) List(ctx, secretOwner interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSecretReader)(nil).List), ctx, secretOwner)
}

// MockJWTParser is a mock of JWTParser interface.
type MockJWTParser struct {
	ctrl     *gomock.Controller
	recorder *MockJWTParserMockRecorder
}

// MockJWTParserMockRecorder is the mock recorder for MockJWTParser.
type MockJWTParserMockRecorder struct {
	mock *MockJWTParser
}

// NewMockJWTParser creates a new mock instance.
func NewMockJWTParser(ctrl *gomock.Controller) *MockJWTParser {
	mock := &MockJWTParser{ctrl: ctrl}
	mock.recorder = &MockJWTParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTParser) EXPECT() *MockJWTParserMockRecorder {
	return m.recorder
}

// Parse mocks base method.
func (m *MockJWTParser) Parse(tokenStr string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", tokenStr)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockJWTParserMockRecorder) Parse(tokenStr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockJWTParser)(nil).Parse), tokenStr)
}
