// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Github/gophkeeper/inernal/usecases/client/sync.go

// package usecases is a generated GoMock package.
package usecases

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/sbilibin2017/gophkeeper/inernal/models"
)

// MockClientLister is a mock of ClientLister interface.
type MockClientLister struct {
	ctrl     *gomock.Controller
	recorder *MockClientListerMockRecorder
}

// MockClientListerMockRecorder is the mock recorder for MockClientLister.
type MockClientListerMockRecorder struct {
	mock *MockClientLister
}

// NewMockClientLister creates a new mock instance.
func NewMockClientLister(ctrl *gomock.Controller) *MockClientLister {
	mock := &MockClientLister{ctrl: ctrl}
	mock.recorder = &MockClientListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientLister) EXPECT() *MockClientListerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockClientLister) List(ctx context.Context, secretOwner string) ([]*models.SecretDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, secretOwner)
	ret0, _ := ret[0].([]*models.SecretDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockClientListerMockRecorder) List(ctx, secretOwner interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClientLister)(nil).List), ctx, secretOwner)
}

// MockServerGetter is a mock of ServerGetter interface.
type MockServerGetter struct {
	ctrl     *gomock.Controller
	recorder *MockServerGetterMockRecorder
}

// MockServerGetterMockRecorder is the mock recorder for MockServerGetter.
type MockServerGetterMockRecorder struct {
	mock *MockServerGetter
}

// NewMockServerGetter creates a new mock instance.
func NewMockServerGetter(ctrl *gomock.Controller) *MockServerGetter {
	mock := &MockServerGetter{ctrl: ctrl}
	mock.recorder = &MockServerGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerGetter) EXPECT() *MockServerGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockServerGetter) Get(ctx context.Context, req *models.SecretGetRequest) (*models.SecretDB, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, req)
	ret0, _ := ret[0].(*models.SecretDB)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockServerGetterMockRecorder) Get(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockServerGetter)(nil).Get), ctx, req)
}

// MockServerSaver is a mock of ServerSaver interface.
type MockServerSaver struct {
	ctrl     *gomock.Controller
	recorder *MockServerSaverMockRecorder
}

// MockServerSaverMockRecorder is the mock recorder for MockServerSaver.
type MockServerSaverMockRecorder struct {
	mock *MockServerSaver
}

// NewMockServerSaver creates a new mock instance.
func NewMockServerSaver(ctrl *gomock.Controller) *MockServerSaver {
	mock := &MockServerSaver{ctrl: ctrl}
	mock.recorder = &MockServerSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerSaver) EXPECT() *MockServerSaverMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockServerSaver) Save(ctx context.Context, req *models.SecretSaveRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockServerSaverMockRecorder) Save(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockServerSaver)(nil).Save), ctx, req)
}

// MockCryptor is a mock of Cryptor interface.
type MockCryptor struct {
	ctrl     *gomock.Controller
	recorder *MockCryptorMockRecorder
}

// MockCryptorMockRecorder is the mock recorder for MockCryptor.
type MockCryptorMockRecorder struct {
	mock *MockCryptor
}

// NewMockCryptor creates a new mock instance.
func NewMockCryptor(ctrl *gomock.Controller) *MockCryptor {
	mock := &MockCryptor{ctrl: ctrl}
	mock.recorder = &MockCryptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCryptor) EXPECT() *MockCryptorMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockCryptor) Decrypt(enc *models.Encrypted) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", enc)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockCryptorMockRecorder) Decrypt(enc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockCryptor)(nil).Decrypt), enc)
}
